{% set name = "gorilla-cli" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gorilla-cli-{{ version }}.tar.gz
  sha256: fb4c87126e4ffdc50a84a06e8001091914bbd083f27118423bfe0567541224e9

build:
  entry_points:
    - gorilla=go_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - halo
    - prompt-toolkit

test:
  imports:
    - go_questionary
  commands:
    - pip check
    # leads to interactive prompt
    #- gorilla --help
  requires:
    - pip

about:
  home: https://github.com/gorilla-llm/gorilla-cli
  summary: LLMs for CLI
  description: |
    Gorilla CLI powers your command-line interactions with a user-centric tool. Simply state your
    objective, and Gorilla CLI will generate potential commands for execution. Gorilla today
    supports ~1500 APIs, including Kubernetes, AWS, GCP, Azure, GitHub, Conda, Curl, Sed, and
    many more. No more recalling intricate CLI arguments!
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
